export const OK = 200;
export const CREATED = 201;
export const UNAUTHORIZED = 401;
export const FORBIDDEN = 403;
export const BAD_REQUEST = 400;
export const NOT_FOUND = 404;
export const CONFLICT = 409;
export const UNPROCESSABLE = 422;
export const INTERNAL_SERVER_ERROR = 500;
export const NOT_IMPLEMENTED = 501;
export const SERVICE_UNAVAILABLE = 503;
export const VERIFY = "please verify your email account please"
export const CATCH = "Hoop an error as occur try again ";
export const ACCOUNT_CREATED = "Account created successfully ";
export const TRANSACTION_ERROR = "Unable to save transaction details ";
export const NOUSER = "we are unable to find a user attached to  this ";
export const VERIFIED = "user have already been verified";
export const SUCESS = "sucessful";
export const UNABLE_TO_UPDATE = "sorry unable to update ";
export const UNABLE_TO_CREATE = "unable to create user account please try again";
export const UPDATED = "update sucessful";
export const EMAIL_ALREADY_EXIST = "A user with that email already exist please try another email"
export const FETCH_ERROR = "unable to fetch all";
export const UNABLE_FIND = "unable to find  with this id";
export const UNABLE_DELETE = "unable to delete please try again ";
export const DELETE_SUCCESS = " deleted successfull";
export const AIRTIME_PAYMENT_INITIATED = 200;
export const INSUFFICENT_BALANCE = 202;
export const NO_CONTENT = 204;

